//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int ID { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string donatename { get; set; }
        public string vk { get; set; }
        public string telegram { get; set; }
    
        public virtual donate donate { get; set; }
    }
}
